produit_homepage:
    path:     /
    defaults: { _controller: ProduitBundle:Default:index }
nouveau_produit:
    path:     /ajouter
    defaults: { _controller: ProduitBundle:Default:ajouter }
Ajouter_promotion:
    path:     /promotion
    defaults: { _controller: ProduitBundle:Promotion:AjouterPromotion }
product_details:
    path:     /details
    defaults: { _controller: ProduitBundle:Default:details  }
shop_produit:
    path:     /shop
    defaults: { _controller: ProduitBundle:Default:shop  }
cart_produit:
    path:     /cart
    defaults: { _controller: ProduitBundle:Default:cart  }
wishlist:
    path:     /wishlist
    defaults: { _controller: ProduitBundle:Default:wishlist  }
Ajouter_Produit:
    path:     /produit
    defaults: { _controller: ProduitBundle:Produit:AjouterProduit  }
produit_artisan_details:
    path:     /artisandetails
    defaults: { _controller: ProduitBundle:Default:detailsartisan  }
detailspromotion:
    path:     /detailerpromotion
    defaults: { _controller: ProduitBundle:Default:detailspromotion  }
addCommentaire:
    path:     /addcommc
    defaults: { _controller: ProduitBundle:Commentaire:addCommentaire  }
Supprimer_produit:
    path:     /supprimer
    defaults: { _controller: ProduitBundle:Produit:supprimerProduit }
detailscome:
    path:     /comm
    defaults: { _controller: ProduitBundle:Default:detailscom }




