admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

addPub:
    path:     /addPub
    defaults: { _controller: AdminBundle:Default:addpub }

allPub:
    path:     /allpub
    defaults: { _controller: AdminBundle:Default:allPub }

ajouterPub:
    path:     /puub
    defaults: { _controller: AdminBundle:Default:addPub }
allreclam:
    path:     /all
    defaults: { _controller: AdminBundle:Default:allreclam }
deletePub:
    path:     /delPub
    defaults: { _controller: AdminBundle:Default:deletePub }
#updatePub:
#    path:     /updatePub
#    defaults: { _controller: AdminBundle:Default:updatePub }