mail:
    resource: "@MailBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /log

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /commerce

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

user:
    resource: '@UserBundle/Resources/config/routing.yml'

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

fos_user_registration_confirmed:
    path: /registration/confirmed
    defaults: { _controller: UserBundle:Default:index }

redirecttohome:
    path: /home
    defaults: { _controller: UserBundle:Default:index }

