ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }

AddToCart:
    path:     /AddToCart
    defaults: { _controller: EcommerceBundle:Default:AddToCart }

RemoveItem:
    path:     /RemoveItem
    defaults: { _controller: EcommerceBundle:Default:removeItem }

UpdateItem:
    path:     /UpdateItem
    defaults: { _controller: EcommerceBundle:Default:updateItem }

ValiderAchat:
    path:     /ValiderAchat
    defaults: { _controller: EcommerceBundle:Default:ValiderAchat }

ApplyCoupon:
    path:     /ApplyCoupon
    defaults: { _controller: EcommerceBundle:Default:ApplyCoupon }

PasserCommande:
    path:     /PasserCommande
    defaults: { _controller: EcommerceBundle:Default:PasserCommande }

ListerCommande:
    path:     /ListerCommande
    defaults: { _controller: EcommerceBundle:Default:listerCommandes }

Payer:
    path:     /Payer
    defaults: { _controller: EcommerceBundle:Default:Payer }
